In [22]:
import numpy
import numpy.matlib
import random

def create_matrix(rows, cols):
    matrix = []
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Ingrese elemento en la posición: ({i+1}, {j+1}): "))
            row.append(element)
        matrix.append(row)
    return matrix

def transpose_matrix(matrix):
    # Use nested list comprehension to transpose the matrix
    transposed_matrix = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
    return transposed_matrix

def is_symmetric(matrix):
    # Check if the matrix is equal to its transpose
    return all(matrix[i][j] == matrix[j][i] for i in range(len(matrix)) for j in range(len(matrix[0])))

# user input

rows = int(input("Ingrese el nùmero de filas: "))
cols = int(input("Ingrese el nùmero de columnas: "))

user_matrix = create_matrix(rows, cols)

print("Su matriz es:")
for row in user_matrix:
    print(row)


'''
user_matrix = [[random.random() for _ in range(3)] for _ in range(3)]
print("Random 3x3 Matrix:")
for row in user_matrix:
    print(row)
'''

Su matriz es:
[1.0, 2.0, 3.0]
[4.0, 5.0, 6.0]
[7.0, 8.0, 9.0]


'\nuser_matrix = [[random.random() for _ in range(3)] for _ in range(3)]\nprint("Random 3x3 Matrix:")\nfor row in user_matrix:\n    print(row)\n'

In [23]:
# traspuesta

transposed_matrix = transpose_matrix(user_matrix)

print("\nMatriz traspuesta:")
for row in transposed_matrix:
    print(row)


Matriz traspuesta:
[1.0, 4.0, 7.0]
[2.0, 5.0, 8.0]
[3.0, 6.0, 9.0]


In [24]:
# simétrica

# Check if matrices are symmetric
print("Matriz simétrica", is_symmetric(user_matrix))


Matriz simétrica False


In [25]:
# cuadrada
print("Matriz cuadrada?", rows == cols)


Matriz cuadrada? True


In [26]:
# triangulares
triangular_superior = numpy.triu(user_matrix)
triangular_inferior = numpy.tril(user_matrix)

print('Triangular superior:')
print(triangular_superior)

print('\nTriangular inferior:')
print(triangular_inferior)


Triangular superior:
[[1. 2. 3.]
 [0. 5. 6.]
 [0. 0. 9.]]

Triangular inferior:
[[1. 0. 0.]
 [4. 5. 0.]
 [7. 8. 9.]]


In [27]:
# diagonal

matriz_diagonal = numpy.diag(user_matrix)
print('Matriz diagonal:')
print(matriz_diagonal)

Matriz diagonal:
[1. 5. 9.]
